apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: astradb-devops
  name: astradb-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astradb-devops
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: astradb-devops
    spec:
      containers:
      - image: dieterfl/astradb-devops
        name: astradb-devops
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: astradb-devops
  name: astradb-devops
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: astradb-devops
  type: ClusterIP
status:
  loadBalancer: {}
