apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: astradb-devops-demo
  name: astradb-devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astradb-devops-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: astradb-devops-demo
    spec:
      containers:
      - image: dieterfl/astradb-devops-demo:latest
        imagePullPolicy: Always
        name: astradb-devops-demo
        env:
          - name: astra_application_token
            valueFrom:
              secretKeyRef:
                name: astrasecrets
                key: astra_application_token
          - name: astra_database_id
            valueFrom:
              secretKeyRef:
                name: astrasecrets
                key: astra_database_id
          - name: astra_database_region
            valueFrom:
              secretKeyRef:
                name: astrasecrets
                key: astra_database_region
          - name: astra_keyspace
            valueFrom:
              secretKeyRef:
                name: astrasecrets
                key: astra_keyspace
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: astradb-devops-demo
  name: astradb-devops-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: astradb-devops-demo
  type: ClusterIP
status:
  loadBalancer: {}
