name: Create Astra Environment
run-name: ${{ github.actor }} is creating a Astra demo env
on: [push]

env:
  AWS_REGION: eu-central-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:
  build:
    name: Create astra db
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
      ASTRA_DB_REGION: ${{ secrets.ASTRA_DB_REGION }}
      ASTRA_DB_NAME: ${{ secrets.ASTRA_DB_NAME }}
      ASTRA_DB_KEYSPACE: ${{ secrets.ASTRA_DB_KEYSPACE }}
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls -lsa
      - run: /bin/bash "./astra-install.sh"
      - run: echo "/home/runner/.astra/cli" >> $GITHUB_PATH
      - run: ls -lsa /home/runner/.astra/cli
#      - run: astra db list --token $ASTRA_DB_APPLICATION_TOKEN
      - run: astra db create $ASTRA_DB_NAME -k $ASTRA_DB_KEYSPACE -r $ASTRA_DB_REGION --if-not-exist --wait --token $ASTRA_DB_APPLICATION_TOKEN
      - run: astra db get demo --key id --token $ASTRA_DB_APPLICATION_TOKEN
 
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew bootBuildImage
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List image
        run: docker images

      - name: Tag image
        run: docker tag dieterfl/spring-music:latest dieterfl/astradb-devops-demo:latest

      - name: Publish image
        run: docker push dieterfl/astradb-devops-demo:latest

      - name: Print image name
        run: echo dieterfl/astradb-devops-demo:latest
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Get kubernetes config
        run: aws eks update-kubeconfig --region eu-central-1 --name test-cluster
        
      - name: Deploy to eks
        run: kubectl apply -f ./deployment.yaml
