name: Create Astra Environment
run-name: ${{ github.actor }} is creating a Astra demo env
on: [push]

jobs:
  build:
    name: Create astra db
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls -lsa
      - run: /bin/bash "./astra-install.sh"
      - run: echo "/home/runner/.astra/cli" >> $GITHUB_PATH
      - run: ls -lsa /home/runner/.astra/cli
      - run: astra db list
#      - run: /home/runner/.astra/cli/astra db create demo -k demo --if-not-exist --wait --token 'AstraCS:ASiSkBRIKnCtOyxvXfQEuWHN:ac9ac7da506be5bcc8ddfdfdb2e19eb4aa68f3b217dbc693f78f7ece805f899d'

