name: Create Astra Environment
run-name: ${{ github.actor }} is creating a Astra demo env
on: [push]

jobs:
  build:
    name: Create astra db
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ls -lsa
      - run: /bin/bash "./astra-install.sh"
      - run: echo "/home/runner/.astra/cli" >> $GITHUB_PATH
      - run: ls -lsa /home/runner/.astra/cli
#      - run: astra db list --token $ASTRA_DB_APPLICATION_TOKEN
      - run: astra db create demo -k demo -r europe-west1 --if-not-exist --wait --token $ASTRA_DB_APPLICATION_TOKEN

