name: Create Astra Environment
run-name: ${{ github.actor }} is creating a Astra demo env
on: [push]

jobs:
  build:
    name: Create astra db
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
      ASTRA_DB_REGION: ${{ secrets.ASTRA_DB_REGION }}
      ASTRA_DB_NAME: ${{ secrets.ASTRA_DB_NAME }}
      ASTRA_DB_KEYSPACE: ${{ secrets.ASTRA_DB_KEYSPACE }}
      
    runs-on: ubuntu-latest

    steps:        
#      - name: Curl rest api
#        uses: wei/curl@v1.1.1    
#        with:
#          args: --request POST --url "https://$ASTRA_DB_ID-$ASTRA_DB_REGION.apps.astra.datastax.com/api/rest/v2/keyspaces/$ASTRA_DB_KEYSPACE/album" --header 'content-type: application/json' --header "x-cassandra-token: $ASTRA_DB_APPLICATION_TOKEN" --data '{"artist": "datastax","genre": "astra","albumid": null,"id": "aa1158cd-1cdd-46c0-8624-63023162c4c3","releaseyear": "2022","title": "stargate","trackcount": 0 }'      
#      - run: curl --request POST --url "https://2ac49d42-c7fc-4a6e-8d24-b4bab23cec09-europe-west1.apps.astra.datastax.com/api/rest/v2/keyspaces/demo/album" --header 'content-type: application/json' --header "x-cassandra-token: AstraCS:OafIOlwMJPuAfUhyqmugCLqH:1a840bc35745e616378a49a1c7e000c6b670c139703d9081f855f1925620fe9a" --data '{"artist": "DataStax","genre": "NoSQL","albumid": "null","id": "aa1158cd-1cdd-46c0-8624-63023162c4c3","releaseyear": "2020","title": "Astra DB","trackcount": "0" }'
      - run: curl --request POST --url "https://2ac49d42-c7fc-4a6e-8d24-b4bab23cec09-$ASTRA_DB_REGION.apps.astra.datastax.com/api/rest/v2/keyspaces/demo/album" --header 'content-type:application/json' --header "x-cassandra-token:AstraCS:OafIOlwMJPuAfUhyqmugCLqH:1a840bc35745e616378a49a1c7e000c6b670c139703d9081f855f1925620fe9a" --data '{"artist":"DataStax","genre":"NoSQL","albumid":null,"id":"aa1158cd-1cdd-46c0-8624-63023162c4c3","releaseyear":"2020","title":"Astra DB","trackcount":0 }'
